# Generated by Django 3.2.5 on 2021-09-04 10:24

from django.db import migrations, models
import home.validators
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArijitAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTime', models.DateTimeField(auto_created=True, blank=True)),
                ('songName', models.CharField(max_length=20)),
                ('songImage', models.ImageField(null=True, upload_to='images/%Y/%m/%d/')),
                ('audioFile', models.FileField(null=True, upload_to='audio/%Y/%m/%d/', validators=[home.validators.audio_only])),
                ('mediaType', models.CharField(choices=[('PLAYBACK', 'Playback'), ('BEAT', 'Beat')], default='so', max_length=15)),
                ('todownload', models.BooleanField(default=False)),
                ('author', models.CharField(default='AnonGuy', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=35)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
